spring.application.name=car-rental-app
server.port=8080

# H2 in-memory database
spring.datasource.url=jdbc:h2:mem:carrentaldb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# vehicle size per car type - easily configurable
vehicle.sedan.count=8
vehicle.suv.count=5
vehicle.van.count=3

springdoc.swagger-ui.path=/swagger-ui.html
logging.level.com.carrental=DEBUG
